services:
  laravelapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: project_kp_karina-laravelapp
    container_name: project_kp_karina-laravelapp
    ports:
      - "9000:9000"
    volumes:
      - /root/project_kp_karina:/var/www/html
    networks:
      - app-network
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel10_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=ADMIN123

  webserver:
    image: nginx:latest
    container_name: project_kp_karina-nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: project_kp_karina-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel10_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ADMIN123
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
